# Widereceiver EDA

In [1]:
import pandas as pd

In [2]:
wrs = pd.read_csv('../Capstone_Scrapping/Capstone_text_files/wide_receiver_18-19.txt')

In [3]:
wrs

,NAME,RTG,TEAM,GP,TGT,REC,TGT/G,YDS,100+ YDS,YDS/REC,TD,LONG,FUM,FUML
0,Leonte Carroo,68,MIA,9,4,2,0.4,94,0,47.0,1,74,0,0
1,Curtis Samuel,77,CAR,13,65,39,5.0,494,0,12.7,5,53,1,1
2,Jake Kumerow,66,GB,5,11,8,2.2,103,0,12.9,1,49,0,0
3,Saeed Blacknall,68,OAK,1,0,0,0.0,0,0,0.0,0,0,0,0
4,Brian Quick,78,WAS,6,3,3,0.5,18,0,6.0,0,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Freddie Martino,62,TB,4,1,0,0.2,0,0,0.0,0,0,0,0
235,Damiere Byrd,72,CAR,8,2,1,0.2,8,0,8.0,0,8,0,0
236,Tommylee Lewis,61,NO,7,3,3,0.4,60,0,20.0,1,28,1,1
237,Kendrick Bourne,77,SF,16,66,42,4.1,487,0,11.6,4,33,0,0
238,Darius Jennings,60,TEN,16,15,11,0.9,101,0,9.2,0,36,0,0

In [4]:
wrs['YDS'] = wrs['YDS'].str.replace(',', '').astype('int64')

In [5]:
wrs.rename(columns=lambda x: x.strip(), inplace = True)

In [6]:
wrs = wrs[wrs['TGT'] > 16].copy()

In [7]:
wrs

,NAME,RTG,TEAM,GP,TGT,REC,TGT/G,YDS,100+ YDS,YDS/REC,TD,LONG,FUM,FUML
1,Curtis Samuel,77,CAR,13,65,39,5.0,494,0,12.7,5,53,1,1
5,Keke Coutee,71,HOU,6,41,28,6.8,287,1,10.2,1,40,0,0
9,Devante Parker,80,MIA,11,47,24,4.3,309,1,12.9,1,46,0,0
11,Keith Kirkwood,65,NO,8,21,13,2.6,209,0,16.1,2,42,0,0
12,Michael Floyd,73,WAS,13,24,10,1.8,100,0,10.0,1,20,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,Marvin Hall,65,ATL,16,19,10,1.2,149,0,14.9,1,47,1,0
227,Chris Moore,74,BAL,16,25,19,1.6,196,0,10.3,1,30,0,0
231,Rashard Higgins,72,CLE,13,54,39,4.2,572,0,14.7,4,40,2,1
232,Alex Erickson,63,CIN,16,29,20,1.8,167,0,8.3,0,28,1,1
237,Kendrick Bourne,77,SF,16,66,42,4.1,487,0,11.6,4,33,0,0

In [8]:
wrs = wrs.groupby('NAME', sort = False).mean()

In [9]:
wrs.drop(columns = ['RTG', 'GP'], axis = 1, inplace = True)

In [10]:
wrs_stats = wrs.copy()

In [11]:
wrs_rank = {}

In [12]:
wrs_rank['YDS_rank'] = wrs['YDS'].rank(ascending = False)

In [13]:
wrs_rank['TGT_rank'] = wrs['TGT'].rank(ascending = False)

In [14]:
wrs_rank['REC_rank'] = wrs['REC'].rank(ascending = False)

In [15]:
wrs_rank['TGT/G_rank'] = wrs['TGT/G'].rank(ascending = False)

In [16]:
wrs_rank['100+ YDS_rank'] = wrs['100+ YDS'].rank(ascending = False)

In [17]:
wrs_rank['YDS/REC_rank'] = wrs['YDS/REC'].rank(ascending = False)

In [18]:
wrs_rank['TD_rank'] = wrs['TD'].rank(ascending = False)

In [19]:
wrs_rank['LONG_rank'] = wrs['LONG'].rank(ascending = False)

In [20]:
wrs_rank['FUM_rank'] = wrs['FUM'].rank()

In [21]:
wrs_rank['FUML_rank'] = wrs['FUML'].rank()

In [22]:
wrs_rank['overall'] = (wrs_rank['TGT_rank'] + wrs_rank['REC_rank'] + wrs_rank['TGT/G_rank'] + wrs_rank['100+ YDS_rank'] +
            wrs_rank['YDS/REC_rank'] + wrs_rank['TD_rank'] + wrs_rank['LONG_rank'] +
            wrs_rank['FUM_rank'] + wrs_rank['FUML_rank'] + wrs_rank['YDS_rank'])/10

In [23]:
wrs_rank = pd.DataFrame(wrs_rank)

In [24]:
wrs_final_rank = {}

In [25]:
wrs_final_rank['final_rank'] = wrs_rank['overall'].rank()

In [26]:
wrs_final_rank = pd.DataFrame(wrs_final_rank)

In [27]:
wrs_final_rank = wrs_final_rank.sort_values('final_rank')

In [28]:
wrs_final_rank.to_csv('../Capstone_csv_file/wrs_final_rank_18-19')

In [29]:
wrs = wrs_stats.merge(wrs_rank, on = 'NAME')

In [30]:
wrs.to_csv('../Capstone_csv_file/wrs_stats_rank_18-19')

In [31]:
wrs

,TGT,REC,TGT/G,YDS,100+ YDS,YDS/REC,TD,LONG,FUM,FUML,...,TGT_rank,REC_rank,TGT/G_rank,100+ YDS_rank,YDS/REC_rank,TD_rank,LONG_rank,FUM_rank,FUML_rank,overall
NAME,,,,,,,,,,,,,,,,,,,,,
Curtis Samuel,65,39,5.0,494,0,12.7,5,53,1,1,...,65.5,64.5,68.0,106.5,70.5,39.5,55.0,95.5,122.0,75.55
Keke Coutee,41,28,6.8,287,1,10.2,1,40,0,0,...,100.5,88.5,30.5,53.5,119.0,118.0,91.5,38.5,54.0,79.60
Devante Parker,47,24,4.3,309,1,12.9,1,46,0,0,...,86.0,99.5,81.0,53.5,64.5,118.0,75.0,38.5,54.0,76.30
Keith Kirkwood,21,13,2.6,209,0,16.1,2,42,0,0,...,138.0,134.5,120.0,106.5,15.0,90.0,85.5,38.5,54.0,90.15
Michael Floyd,24,10,1.8,100,0,10.0,1,20,0,0,...,133.5,142.5,133.0,106.5,124.0,118.0,139.5,38.5,54.0,113.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marvin Hall,19,10,1.2,149,0,14.9,1,47,1,0,...,142.0,142.5,144.0,106.5,34.5,118.0,72.0,95.5,54.0,104.50
Chris Moore,25,19,1.6,196,0,10.3,1,30,0,0,...,130.0,115.5,137.5,106.5,116.5,118.0,111.5,38.5,54.0,105.00
Rashard Higgins,54,39,4.2,572,0,14.7,4,40,2,1,...,76.5,64.5,84.5,106.5,38.0,57.5,91.5,126.5,122.0,82.45
Alex Erickson,29,20,1.8,167,0,8.3,0,28,1,1,...,120.0,111.0,133.0,106.5,139.5,139.5,116.5,95.5,122.0,121.35
Kendrick Bourne,66,42,4.1,487,0,11.6,4,33,0,0,...,63.5,57.0,86.5,106.5,95.5,57.5,106.0,38.5,54.0,73.60