# Quarterback TD Rank

In [1]:
import pandas as pd

In [2]:
qbs = pd.read_csv('../Capstone_csv_file/qbs_stats_rank_17-18', index_col = 'NAME')

In [3]:
qbs.head()

,COMP,ATT,ATT/G,YDS,300+ YDS,COMP%,YDS/ATT,YDS/COMP,TD,INT,...,COMP%_rank,YDS/ATT_rank,YDS/COMP_rank,TD_rank,INT_rank,QBR_rank,LONG_rank,SACKS_rank,SACK YDS_rank,FUML_rank
NAME,,,,,,,,,,,,,,,,,,,,,
Tom Brady,385,581,36.3,4577,6,66.3,7.9,11.9,32,8,...,12.0,10.5,12.0,3.0,37.0,2.0,26.5,10.0,14.0,45.0
Aaron Rodgers,154,238,34.0,1675,3,64.7,7.0,10.9,16,6,...,14.5,22.5,38.5,24.0,27.5,30.0,17.0,26.0,21.0,24.5
Russell Wilson,339,553,34.6,3983,3,61.3,7.2,11.7,34,11,...,32.5,20.0,16.5,1.0,42.5,7.5,14.5,4.0,2.0,45.0
Drew Brees,386,536,33.5,4334,3,72.0,8.1,11.2,23,8,...,4.0,5.5,30.0,11.0,37.0,1.0,34.5,31.0,28.0,9.0
Matt Ryan,342,529,33.1,4095,4,64.7,7.7,12.0,20,12,...,14.5,13.0,9.5,17.0,45.0,12.0,3.0,22.5,24.0,45.0

In [4]:
qbs.rename(columns=lambda x: x.strip(), inplace = True)

In [5]:
qbs = qbs[['TD', 'TD_rank']].copy()

In [6]:
qbs = qbs.sort_values('TD_rank')

In [7]:
qbs.to_csv('../Capstone_csv_file/qbs_td_rank_17-18')