# Quarterbacks EDA

In [1]:
import pandas as pd

In [2]:
qbs = pd.read_csv('../Capstone_Scrapping/Capstone_text_files/quarter_back.txt')
qbs.head()

,NAME,RTG,TEAM,GP,COMP,ATT,ATT/G,YDS,300+ YDS,COMP%,YDS/ATT,YDS/COMP,TD,INT,QBR,LONG,SACKS,SACK YDS,FUML
0,Luke Falk,68,NYJ,3,47,73,24.3,416,0,64.4%,5.7,8.9,0,3,61.4,36,16,96,1
1,Brandon Allen,70,DEN,3,39,84,28.0,515,0,46.4%,6.1,13.2,3,2,18.3,75,9,59,0
2,Drew Lock,72,DEN,5,100,156,31.2,"1,020",1,64.1%,6.5,10.2,7,3,92.4,48,5,26,1
3,David Fales,64,NYJ,2,0,0,0.0,0,0,0%,0.0,0.0,0,0,0.0,0,1,7,0
4,Devlin Hodges,73,PIT,8,100,160,20.0,"1,063",0,62.5%,6.6,10.6,5,8,45.9,79,15,102,1

In [3]:
qbs['COMP%'] = qbs['COMP%'].str.replace('%', '').astype('float64')

qbs['YDS'] = qbs['YDS'].str.replace(',', '').astype('int64')

In [4]:
qbs.rename(columns=lambda x: x.strip(), inplace = True)

In [5]:
qbs.columns

Index(['NAME', 'RTG', 'TEAM', 'GP', 'COMP', 'ATT', 'ATT/G', 'YDS', '300+ YDS',
       'COMP%', 'YDS/ATT', 'YDS/COMP', 'TD', 'INT', 'QBR', 'LONG', 'SACKS',
       'SACK YDS', 'FUML'],
      dtype='object')

In [6]:
qbs.drop(columns = ['RTG', 'TEAM', 'GP'], inplace = True)

In [7]:
qbs.head(1)

,NAME,COMP,ATT,ATT/G,YDS,300+ YDS,COMP%,YDS/ATT,YDS/COMP,TD,INT,QBR,LONG,SACKS,SACK YDS,FUML
0,Luke Falk,47,73,24.3,416,0,64.4,5.7,8.9,0,3,61.4,36,16,96,1

In [8]:
qbs = qbs[qbs['ATT'] > 21].copy()

In [9]:
qbs.dtypes

NAME         object
COMP          int64
ATT           int64
ATT/G       float64
YDS           int64
300+ YDS      int64
COMP%       float64
YDS/ATT     float64
YDS/COMP    float64
TD            int64
INT           int64
QBR         float64
LONG          int64
SACKS         int64
SACK YDS      int64
FUML          int64
dtype: object

In [10]:
qbs_stats = qbs.copy()

In [11]:
qbs['COMP_rank'] = qbs['COMP'].rank(ascending = False)

qbs['ATT_rank'] = qbs['ATT'].rank(ascending = False)

qbs['ATT/G_rank'] = qbs['ATT/G'].rank(ascending = False)

qbs['YDS_rank'] = qbs['YDS'].rank(ascending = False)

qbs['300+ YDS_rank'] = qbs['300+ YDS'].rank(ascending = False)

qbs['COMP%_rank'] = qbs['COMP%'].rank(ascending = False)

qbs['YDS/ATT_rank'] = qbs['YDS/ATT'].rank(ascending = False)

qbs['YDS/COMP_rank'] = qbs['YDS/COMP'].rank(ascending = False)

qbs['TD_rank'] = qbs['TD'].rank(ascending = False)

qbs['INT_rank'] = qbs['INT'].rank()

qbs['QBR_rank'] = qbs['QBR'].rank(ascending = False)

qbs['LONG_rank'] = qbs['LONG'].rank(ascending = False)

qbs['SACKS_rank'] = qbs['SACKS'].rank()

qbs['SACK YDS_rank'] = qbs['SACK YDS'].rank()

qbs['FUML_rank'] = qbs['FUML'].rank()

In [12]:
qbs.to_csv('../Capstone_csv_file/qbs_stats_rank_19-20', index = False)

In [13]:
qbs_rank = qbs.drop(columns = ['COMP', 'ATT', 'ATT/G', 'YDS', '300+ YDS',
                               'COMP%', 'YDS/ATT', 'YDS/COMP', 'TD', 'INT',
                               'QBR', 'LONG', 'SACKS', 'SACK YDS', 'FUML'])

In [14]:
qbs_rank['overall'] = (qbs['COMP_rank']+qbs['ATT_rank']+qbs['ATT/G_rank']+qbs['YDS_rank']+ 
                          qbs['300+ YDS_rank']+qbs['COMP%_rank']+qbs['YDS/ATT_rank']+
                          qbs['YDS/COMP_rank']+qbs['TD_rank']+qbs['QBR_rank']+qbs['LONG_rank']+
                          qbs['SACKS_rank']+qbs['SACK YDS_rank']+qbs['FUML_rank'])/14

In [15]:
qbs_rank = qbs_rank.groupby('NAME', sort = False).mean()

In [16]:
qbs_final_rank = {}

In [17]:
qbs_final_rank['final_rank'] = qbs_rank['overall'].rank()

In [18]:
qbs_final_rank = pd.DataFrame(qbs_final_rank)

In [19]:
qbs_final_rank = qbs_final_rank.rank()

In [20]:
qbs_final_rank = qbs_final_rank.sort_values('final_rank')

In [21]:
qbs_final_rank

                    final_rank
NAME
Dak Prescott               1.0
Patrick Mahomes            2.0
Philip Rivers              3.0
Jameis Winston             4.5
Jared Goff                 4.5
Matt Ryan                  6.0
Drew Brees                 7.0
Jimmy Garoppolo            8.0
Derek Carr                 9.5
Russell Wilson             9.5
Tom Brady                 11.0
Kirk Cousins              12.0
Lamar Jackson             13.0
Aaron Rodgers             14.0
Ryan Tannehill            15.0
Matthew Stafford          16.5
Deshaun Watson            16.5
Carson Wentz              18.0
Kyler Murray              19.0
Baker Mayfield            20.0
Ryan Fitzpatrick          21.0
Eli Manning               22.0
Gardner Minshew           23.0
Sam Darnold               24.0
Andy Dalton               25.0
Drew Lock                 26.0
Matt Schaub               27.0
Marcus Mariota            28.5
Teddy Bridgewater         28.5
Daniel Jones              30.0
Joe Flacco                31.0
Mitch Trubisky            32.0
Mason Rudolph             33.0
Case Keenum               34.0
Jacoby Brissett           35.0
Kyle Allen                36.0
Matt Moore                37.0
Devlin Hodges             38.0
Jeff Driskel              39.0
Josh Allen                40.0
David Blough              41.0
Cam Newton                42.0
Brandon Allen             43.0
Dwayne Haskins            44.0
Nick Foles                45.0
Chase Daniel              46.0
Matt Barkley              47.0
Ben Roethlisberger        48.0
Luke Falk                 49.0
Ryan Finley               50.5
Robert Griffin III        50.5
Colt McCoy                52.0
AJ McCarron               53.0
Brian Hoyer               54.0
Josh Rosen                55.0
Will Grier                56.0

In [22]:
qbs_final_rank.to_csv('../Capstone_csv_file/qbs_final_rank_19-20')