# Quarterback TD Rank

In [1]:
import pandas as pd

In [2]:
qbs = pd.read_csv('../Capstone_csv_file/qbs_stats_rank_18-19', index_col = 'NAME')

In [3]:
qbs.head()

,COMP,ATT,ATT/G,YDS,300+ YDS,COMP%,YDS/ATT,YDS/COMP,TD,INT,...,COMP%_rank,YDS/ATT_rank,YDS/COMP_rank,TD_rank,INT_rank,QBR_rank,LONG_rank,SACKS_rank,SACK YDS_rank,FUML_rank
NAME,,,,,,,,,,,,,,,,,,,,,
Nick Mullens,176,274,34.2,2277,2,64.2,8.3,12.9,13,10,...,26.5,7.0,6.5,27.5,35.0,17.0,4.0,33.0,32.0,8.5
Matt Barkley,15,25,25.0,232,0,60.0,9.3,15.5,2,0,...,42.5,2.0,1.0,46.0,1.5,49.0,42.5,54.0,53.5,8.5
Josh Johnson,52,91,22.8,590,0,57.1,6.5,11.3,3,4,...,48.0,42.0,22.5,42.0,18.0,29.0,9.0,42.0,41.0,8.5
Jameis Winston,244,378,34.4,2992,5,64.6,7.9,12.3,19,14,...,24.0,13.0,10.5,21.5,50.0,25.0,31.5,21.0,24.5,40.0
Derek Anderson,42,70,35.0,465,0,60.0,6.6,11.1,0,4,...,42.5,39.0,28.5,54.0,18.0,52.0,47.0,49.5,50.5,31.0

In [4]:
qbs.rename(columns=lambda x: x.strip(), inplace = True)

In [5]:
qbs = qbs[['TD', 'TD_rank']].copy()

In [6]:
qbs = qbs.sort_values('TD_rank')

In [7]:
qbs.to_csv('../Capstone_csv_file/qbs_td_rank_18-19')