# QBS Salary Stats Rank

In [1]:
import pandas as pd

In [2]:
salary = pd.read_csv('../Capstone_csv_file/salary_edited_to_fit_19-20')

In [3]:
qbs = pd.read_csv('../Capstone_csv_file/qbs_stats_rank_19-20')

qbs.set_index('NAME', inplace = True)

qbs_final_salary = qbs.merge(salary, on = 'NAME')

qbs_final_salary.set_index('NAME', inplace = True)

In [4]:
qbs_final_salary.head()

,COMP,ATT,ATT/G,YDS,300+ YDS,COMP%,YDS/ATT,YDS/COMP,TD,INT,...,YDS/ATT_rank,YDS/COMP_rank,TD_rank,INT_rank,QBR_rank,LONG_rank,SACKS_rank,SACK YDS_rank,FUML_rank,salary
NAME,,,,,,,,,,,,,,,,,,,,,
Drew Lock,100,156,31.2,1020,1,64.1,6.5,10.2,7,3,...,40.5,46.0,34.0,15.0,9.0,40.0,6.5,5.0,19.0,1752704
Patrick Mahomes,319,484,34.6,4031,7,65.9,8.3,12.6,26,5,...,5.0,7.5,10.0,25.0,12.0,7.5,26.0,26.0,29.0,4106447
Tom Brady,373,613,38.3,4057,5,60.8,6.6,10.9,24,8,...,37.0,32.5,13.5,38.0,13.0,30.0,33.5,35.0,19.0,23000000
Drew Brees,281,378,34.4,2979,5,74.3,7.9,10.6,27,4,...,10.5,41.0,6.0,19.0,26.0,28.0,18.5,17.5,7.5,25000000
Matt Ryan,408,616,41.1,4466,11,66.2,7.2,10.9,26,14,...,18.0,32.5,10.0,51.0,17.0,1.0,55.0,54.0,50.0,30000000

In [5]:
qbs_final_salary.to_csv('../Capstone_csv_file/qbs_stats_salary_19-20')