# Tightends 100+ Yds Rank

In [1]:
import pandas as pd

In [2]:
tes = pd.read_csv('../Capstone_csv_file/tes_stats_rank_18-19', index_col = 'NAME')

In [3]:
tes.head()

,TGT,REC,TGT/G,100+ YDS,YDS/REC,TD,LONG,FUM,FUML,TGT_rank,REC_rank,TGT/G_rank,100+ YDS_rank,YDS/REC_rank,TD_rank,LONG_rank,FUM_rank,FUML_rank,overall
NAME,,,,,,,,,,,,,,,,,,,
Demetrius Harris,25,12,1.7,0,13.7,3,35,0,0,48.0,58.5,51.5,37.5,7.0,21.5,28.0,22.5,25.5,33.333333
Hayden Hurst,23,13,1.9,0,12.5,1,32,0,0,52.0,55.5,48.5,37.5,16.0,45.5,33.0,22.5,25.5,37.333333
Dan Arnold,19,12,1.9,0,12.5,1,25,1,0,58.0,58.5,48.5,37.5,16.0,45.5,49.0,51.5,25.5,43.333333
Vance McDonald,73,50,4.9,1,12.2,4,75,2,1,12.0,12.0,14.0,9.0,18.5,12.5,2.5,60.5,56.0,21.888889
Anthony Firkser,20,19,2.0,0,11.8,1,28,0,0,55.0,47.0,46.5,37.5,22.5,45.5,42.5,22.5,25.5,38.277778

In [4]:
tes = tes[['100+ YDS', '100+ YDS_rank']]

In [5]:
tes = tes.sort_values('100+ YDS_rank')

In [6]:
tes.to_csv('../Capstone_csv_file/tes_100+_yds_rank_18-19')