# Tightends Tgt/G Rank

In [1]:
import pandas as pd

In [2]:
tes = pd.read_csv('../Capstone_csv_file/tes_stats_rank_17-18', index_col = 'NAME')

In [3]:
tes.head()

,TGT,REC,TGT/G,100+ YDS,YDS/REC,TD,LONG,FUM,FUML,TGT_rank,REC_rank,TGT/G_rank,100+ YDS_rank,YDS/REC_rank,TD_rank,LONG_rank,FUM_rank,FUML_rank,overall
NAME,,,,,,,,,,,,,,,,,,,
Rob Gronkowski,105,69,7.5,3,204.7,8,53,1,0,6.0,5.0,4.0,2.0,2.0,3.5,9.5,53.0,26.0,12.333333
Greg Olsen,38,17,5.4,1,60.9,1,30,0,0,34.0,44.5,12.5,7.0,60.0,50.0,40.0,22.5,26.0,32.944444
Travis Kelce,122,83,8.1,4,177.0,8,44,0,0,1.0,1.0,1.0,1.0,11.0,3.5,16.0,22.5,26.0,9.222222
Jimmy Graham,95,57,5.9,0,123.8,10,33,0,0,7.0,9.5,7.0,38.5,32.0,1.0,32.5,22.5,26.0,19.555556
Delanie Walker,111,74,6.9,0,173.9,3,42,2,2,3.0,3.5,6.0,38.5,12.0,23.5,19.5,63.5,64.0,25.944444

In [4]:
tes = tes[['TGT/G', 'TGT/G_rank']]

In [5]:
tes = tes.sort_values('TGT/G_rank')

In [6]:
tes.to_csv('../Capstone_csv_file/tes_tgt_g_rank_17-18')